### ISSUE TITLE
Downloading files are moved to new folder which cause downloading to fail

### ISSUE THREAD

**Issue by thisisjaymehta** [thisisjaymehta/python-automatic-file-organization#1]
The code moves new files as soon as they are created.
This creates an issue when a browser is downloading a file to that folder, script will move the file as soon as download starts and so in browser download will fail.
Need a mechanism to check if file is currently in use by some other process before moving.

**Comment by khushit-shah** [comment]
get the last modified time of the file. If the file was not modified for a certain amount of time(i.e. minute) organize it. 
checkout `os.stat(FILE_PATH).st_mtime`

**Comment by thisisjaymehta** [comment]
Found another way where you can add extensions that you want to skip, to the extension list under `SKIP` key.
Thanks for the help.
